[package]
name = "adi"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
log = "0.4.29"
