[package]
name = "apple-codesign"
version = "0.1.0"
edition = "2024"

[dependencies]
plist.workspace = true

tokio.workspace = true
lief = "0.17"
sha1 = "0.11.0-rc.3"
sha2 = "0.11.0-rc.3"
futures = "0.3.31"
log = "0.4.28"
